jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
spring:
  servlet:
    multipart:
      maxFileSize: 100MB # 파일 하나의 최대 크기
      maxRequestSize: 300MB  # 한 번에 최대 업로드 가능 용량
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://develop.sjkim.net:3306/carwash?autoReconnect=true
    username: root
    password: ehsRktm4577!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 177000

  jpa:
    database: mysql   # 추가 해준 부분
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create # 자동으로 테이블을 만들어줌 애플리케이션 실행시에 다 지우고 다시 실행
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true